### PR TITLE
#2 Develop merger to main

### PR DESCRIPTION
**Pull request by Haohaoscreamandrun**
Server running checked, 7/16 progress merger to main branch

### CODE REVIEW

**Review by loshuyen — APPROVED** [review]
OK.

**Review by loshuyen — APPROVED** [review]
👍

**Review by loshuyen — APPROVED** [review]
Good.

**Comment by bibbygreen** [comment]
OK

**Review by bibbygreen — APPROVED** [review]
OK

**Review by bibbygreen — APPROVED** [review]
ok

**Review by LinSky0323 — APPROVED** [review]
ok done

**Review by loshuyen — APPROVED** [review]
OK

**Pull request merged**
